name: 'My TypeScript Github action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  name:
    required: true
    description: "your name here"
  milliseconds:
    required: true
    description: 'input description here'
  token:
    required: false
    description: 'token of github'
    default: ${{ github.token }}
outputs:
  time:
    description: time slept
runs:
  using: 'node16'
  main: 'dist/index.js'
